name: Deploy to Play Store
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "beta"
        type: choice
        options:
          - beta
          - promote_to_production
          - production

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        if: ${{ github.event.inputs.lane != 'promote_to_production' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        if: ${{ github.event.inputs.lane != 'promote_to_production' }}
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Calculate version number
        if: ${{ github.event.inputs.lane != 'promote_to_production' }}
        run: readarray -d . -t v <<< "${{ steps.tag_version.outputs.new_version }}";printf -v m '%d%03d%03d' "${v[0]}" "${v[1]}" "${v[2]/$'\n'/""}";echo "VERSION_NUMBER=$(echo $m)" >> $GITHUB_ENV;
      - name: Echo version
        if: ${{ github.event.inputs.lane != 'promote_to_production' }}
        run: echo $VERSION_NUMBER
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        if: ${{ github.event.inputs.lane != 'promote_to_production' }}
        uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: stable
      - run: flutter doctor

      # Checkout code and get packages.
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        if: ${{ github.event.inputs.lane != 'promote_to_production' }}
      - run: flutter pub get

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@c4fe7bd15ddbfcd5e07e47bf2f2cae90581d6091
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        if: ${{ github.event.inputs.lane != 'promote_to_production' }}
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      # Build and deploy with Fastlane (by default, to beta track) 🚀.
      # Naturally, promote_to_production only deploys.
      - run: bundle exec fastlane ${{ github.event.inputs.lane }} name:${{ steps.tag_version.outputs.new_version }} number:$VERSION_NUMBER
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android
